include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    body_might_complete_normally_catch_error: ignore
  language:
    strict-inference: true
    strict-raw-types: true

  exclude:
    - lib/swagger/**
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.gr.dart
    - lib/**.gen.dart
    - lib/**.mocks.dart
    - build/**
    - .dart_tool/**

linter:
  rules:
    # 💡 Readability & Formatting
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_expression_function_bodies: true
    unnecessary_this: true
    unnecessary_brace_in_string_interps: true
    unnecessary_string_interpolations: true
    avoid_escaping_inner_quotes: true
    prefer_interpolation_to_compose_strings: true
    leading_newlines_in_multiline_strings: true
    prefer_adjacent_string_concatenation: true
    sort_unnamed_constructors_first: true
    sort_constructors_first: true
    curly_braces_in_flow_control_structures: true
    #lines_longer_than_80_chars: true
    require_trailing_commas: true
    directives_ordering: true

    # 🚫 Anti-patterns
    avoid_print: true
    avoid_dynamic_calls: true
    avoid_returning_null_for_void: true
    avoid_types_as_parameter_names: true
    avoid_empty_else: true
    avoid_classes_with_only_static_members: true
    avoid_function_literals_in_foreach_calls: true
    avoid_annotating_with_dynamic: true
    avoid_init_to_null: true
    avoid_return_types_on_setters: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_field_initializers_in_const_classes: true
    avoid_shadowing_type_parameters: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_null_checks_in_equality_operators: true
    avoid_types_on_closure_parameters: true
    avoid_double_and_int_checks: true
    avoid_unused_constructor_parameters: true
    avoid_catching_errors: true
    avoid_slow_async_io: true
    avoid_multiple_declarations_per_line: true
    avoid_web_libraries_in_flutter: true
    use_build_context_synchronously: false
    # 🔍 Code Safety
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    use_key_in_widget_constructors: true
    use_rethrow_when_possible: true
    use_is_even_rather_than_modulo: true
    use_setters_to_change_properties: true
    use_to_and_as_if_applicable: true
    use_string_buffers: true
    null_check_on_nullable_type_parameter: true
    unnecessary_null_checks: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    use_if_null_to_convert_nulls_to_bools: true
    omit_local_variable_types: true
    prefer_typing_uninitialized_variables: false
    prefer_final_parameters: false
    library_private_types_in_public_api: false
    # ✅ Flutter-Specific
    flutter_style_todos: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
    avoid_unnecessary_containers: true
    avoid_relative_lib_imports: true
    prefer_relative_imports: false
    always_use_package_imports: true
    no_logic_in_create_state: true

    # ✅ Best Practices
    type_annotate_public_apis: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    prefer_function_declarations_over_variables: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_generic_function_type_aliases: true
    tighten_type_of_initializing_formals: true
    prefer_initializing_formals: true
    cascade_invocations: true
    prefer_collection_literals: true
    prefer_spread_collections: true
    control_flow_in_finally: true
    unnecessary_statements: true
    join_return_with_assignment: true
    only_throw_errors: true
    await_only_futures: true

    # Misc
    constant_identifier_names: true
    non_constant_identifier_names: true
    hash_and_equals: true
    slash_for_doc_comments: true
    camel_case_extensions: true
    camel_case_types: true
    package_names: true
    library_names: true
    valid_regexps: true
    recursive_getters: true
    prefer_mixin: true
    noop_primitive_operations: true